project:
  type: website
  output-dir: _site

website:
  title: "CoT Unfaithfulness Replication"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Full Report"
        href: analysis.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true

execute:
  freeze: auto
